### ISSUE TITLE
Language Clarifications

### ISSUE THREAD

**Issue by aaronsaray** [rectorphp/getrector.org#1037]
I have the following questions from the pages of the marketing site. Once these are answered, I will create another PR with remaining grammar and localization changes.

* homepage: `We help 5+ years PHP companies to get the most of the code they already have.` to me, it's unclear what `5+ years` is meant to describe. Are these companies that have been in business for 5+ years? Companies that have used PHP for 5+ years? Companies with code that is at least 5 years old? Or has the rector team been helping PHP companies for at least 5 years (how long you've been around / consulting)
* homepage, faq: `The way we work is always finished.` - I'm not sure what this means.  The context makes it sound like you mean to say that you never submit work-in-progress pull requests maybe? Or that you mean you only make small changes? Can you clarify?
* homepage, faq: `In a week there is 25 merged pull-request and your project is forever improved.` - I'm just confirming, you're intending to say that in a week, there could be up to 25 pull requests from the rector team, and the client has likely merged those in? The intent is to confirm that you do only small code changes at a time?
* hire team: `We help them to cut feature costs to fractions and make their teams productive again.` - I assume 'cut feature costs' means that you help to reduce the cost of development on features, correct?
* do you prefer UK English or American English? Do you require one or is either ok? For example `standardisation` is the UK spelling (which is ok). Just want to confirm these types are ok to leave alone or if you'd like them changed.

After I receive these clarifications, I will submit another pull request.

**Comment by TomasVotruba** [comment]
Hi @aaronsaray !

Thanks for working on this :) I'll briefly reply:

1. I see the number is missleading. I think it would be better to say "We help successfuly and growing companies...". The point was rather we help 5-15 years old companies, that have some technical debt, are stable and grow for a long time.

2. This means all our work is ready to merge in any point of time. There is no WIP pull-request for 3 months, but rather tiny isolated and complete work in small PRs.
 
3.   > and the client has likely merged those in? The intent is to confirm that you do only small code changes at a time?

Yes, exactly!

4. > reduce the cost of development on features

Yes :+1: 

5. I think the American one, as there are more potential clients with legacy projects.

**Comment by aaronsaray** [comment]
Thanks for the clarifications. Submitted PR #1041 with these changes as well as others.
