### ISSUE TITLE
nette/utils is required for the custom rule example

### ISSUE THREAD

**Issue by reneroboter** [rectorphp/getrector.org#1044]
I created my first own Rector and by the way I realised that the original example depend on `nette/utils`. I guess when someone unexpired will try this example he will be confused, because after installing rector as dev dependency you don't have `nette/utils`. 

So my recommendation would be to get rid of `nette/utils` or add a hint that you've to install `nette/utils` as dependency.

https://github.com/rectorphp/getrector.org/blame/main/data/docs/custom-rule.md#L19

**Comment by TomasVotruba** [comment]
Hi, I think it would be better to remove the package from example.
Could you send a PR to handle it?

**Comment by reneroboter** [comment]
@TomasVotruba I'll do it :)

**Comment by TomasVotruba** [comment]
@reneroboter Thank you :hugs:
