### ISSUE TITLE
Different output when running locally in docker or online demo

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/getrector.org#133]
Demo: https://getrector.org/demo/a932028e-593c-41e0-addb-4efce9e66821#result (see https://github.com/rectorphp/rector/issues/2842)

<img width="1325" alt="Screenshot 2020-02-16 10 36 47" src="https://user-images.githubusercontent.com/3995003/74602406-622c0000-50a8-11ea-9b7c-acd73ed04c09.png">

**Comment by TomasVotruba** [comment]
Output is the same, just highlight is different

**Comment by TomasVotruba** [comment]
Probably solved with latest tag using dev-master, right?
