### ISSUE TITLE
Add webhook that will trigger docker pull for demo image

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/getrector.org#134]
Right now, demo is updated on every deploy.

Though when we do not deploy for few days or weeks docker container of demo gets outdated.

Few ideas:
- Run cron every few hours
- Trigger automatically when new docker image is published
- Display used version after demo form submission, so user knows what version was used

Some context here: https://github.com/rectorphp/rector/issues/2841#issuecomment-586955841

**Comment by JanMikes** [comment]
Added cron that will be triggered every hour:
```
0 * * * * docker pull rector/rector-secured:latest
```

Apart of that it would be nice to add webhook that will be triggered after new image with latest tag is built.

**Comment by TomasVotruba** [comment]
Thank you
