### ISSUE TITLE
Delete uploaded code on getrector.org/demo for security/privacy reason

### ISSUE THREAD

**Issue by mayerwin** [rectorphp/getrector.org#151]
How long does it take for code uploaded on https://getrector.org/demo to be purged? 
I was surprised to see a permalink was created upon trying the demo, with no apparent possibility to delete it manually even though it may contain sensitive data.

**Comment by TomasVotruba** [comment]
We don't purge data, nor use them for any other purpose yet. We plan to detect most common bugs and solve them, so people don't have to report them on Github issues.

It's not required for demo to run to contain real code. I recommend using pseudo code, with only 10-20 lines, like you would while using services like 3v4l.org.

For all private sensitive code run Rector locally. Never add passwords to any online service.

Nevertheless, if there is some sensitive code from your side, send email to @JanMikes with links to remove on https://getrector.org/contact

We'll remove them for this case manually, but do not send any exposable code in the future.

**Comment by JanMikes** [comment]
We were in touch via email, i can confirm that code sample has been deleted.

If we receive more requests like this, i would consider implementing some delete feature.
