### ISSUE TITLE
Try Rector Online shows blank result

### ISSUE THREAD

**Issue by nobuf** [rectorphp/getrector.org#169]
Steps to reproduce:

- Go https://getrector.org/demo
- Hit "Process!"

<img width="854" alt="Try Rector Online | Rector - Automated Way to Instantly Upgrade and Refactor any PHP code 2020-08-15 14-49-57" src="https://user-images.githubusercontent.com/211832/90306331-0f23f000-df07-11ea-8fd3-df76ee79f51e.png">

I expect I'd see refactored code in the Result section. I'm seeing the same blank result with the latest Google Chrome and Firefox on macOS.

I'm not sure if this is happening from https://github.com/rectorphp/rector/tree/94064a3 or earlier.

Thanks!

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting :+1:
