### ISSUE TITLE
Broken Rector count

### ISSUE THREAD

**Issue by orklah** [rectorphp/getrector.org#186]
The rector count at the bottom of the website is broken.

I think this commit is the cause:
https://github.com/rectorphp/rector/commit/a7705ed0a59c7c0ff8619c07ec48f489fb90787f#diff-0ca070f5c8b325633495e75e04a81ff06cf16c398d1480526bebeaadcc737928

It removed the count at the top which was matched with a regex to display the count

**Comment by TomasVotruba** [comment]
Hi,

thanks for reporting :+1: 

Dare to fix it?

**Comment by orklah** [comment]
I'm not sure why the format changed and how to fix it. Maybe with a few hints?

**Comment by TomasVotruba** [comment]
The format changed, because we switched to https://github.com/symplify/rule-doc-generator

I guess better than getting number would be counting number of rules in the file
