### ISSUE TITLE
Ast visualization

### ISSUE THREAD

**Issue by staabm** [rectorphp/getrector.org#189]
What do you think about adding a button to the get-rector demo, which when clicked generates a graphical represenation of the demo code with https://github.com/ircmaxell/php-ast-visualizer?

It could look like 

https://github.com/ircmaxell/php-ast-visualizer/blob/master/demo.png

**Comment by TomasVotruba** [comment]
That would be something unrelated to Rector and probably confusing for most users that don't work with nodes.

Should be pretty easy to set up on your website website though.
