### ISSUE TITLE
[demo] Output is capped when multiple classes/interfaces

### ISSUE THREAD

**Issue by ruudk** [rectorphp/getrector.org#245]
See https://getrector.org/demo/3988c72f-7a5b-4f9d-ba87-1eb209e6d1d5

```php
<?php
interface FormTypeInterface
{
    public function getTag() : string;
}

final class DemoFile
{
    /**
     * @var iterable|FormTypeInterface[]
     */
    private $formTypes;

    /**
     * @param FormTypeInterface[] $formTypes
     */
    public function __construct(iterable $formTypes)
    {
        $this->formTypes = $formTypes;
    }
}
```

shows like this:
<img width="1001" alt="Screenshot 2021-01-30 at 13 47 10@2x" src="https://user-images.githubusercontent.com/104180/106356662-ab00b700-6301-11eb-9760-83dba79b3ed2.png">

**Comment by TomasVotruba** [comment]
Test would be great to cover this :+1:

**Comment by ruudk** [comment]
See https://github.com/rectorphp/getrector.org/pull/253

**Comment by TomasVotruba** [comment]
Closed by https://github.com/rectorphp/getrector.org/pull/253

Tip for next time automation:
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
