### ISSUE TITLE
[ERROR] File "/project/rector.php" was not found on demo submit

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/getrector.org#265]
@JanMikes So I tried the steps, but same result:

```bash
git clone ...
sudo docker-compose up
```

- the css loads correctly :heavy_check_mark: 
- the form failed :x: 

I tried:

```bash
sudo bin/pull-docker-images.sh
sudo docker-compose up
```

- the form failed same way :x:

**Comment by JanMikes** [comment]
Hi, please i need a little more info from you to understand why you face this issue:
- What is your local absolute path to the project?
- The most important part, please what is value of `$HOST_DEMO_DIR` inside of docker container (easiest way is `docker exec -it <CONTAINERID> echo $HOST_DEMO_DIR`, find container id by running `docker ps` )

Based on your answers i should be able to understand why it does not work for you.

Thank you!

**Comment by TomasVotruba** [comment]
Thanks for copy-paste instructions!

- 1. It's: `/var/www/getrector.org
- 2. When I run  `docker exec -it 7af47e12693e echo $HOST_DEMO_DIR`, it seems empty:

![image](https://user-images.githubusercontent.com/924196/107633011-9e685100-6c67-11eb-84c3-0b58eab64bfb.png)

**Comment by JanMikes** [comment]
Ok, it is root cause of the problem.

Please:
- `git fetch -p && git checkout issue-265/docker-compose-do-not-use-envfile`
- `docker-compose down`
- `docker-compose up`
- `docker exec -it getrectororg_web_1 echo $HOST_DEMO_DIR`

Now if you will see output it gets fixed, otherwise we are doomed and i will have to debug more or find another solution 😄 

(hotfix for your local environment is to create `.env.local` and pust `HOST_DEMO_DIR=/var/www/getrector.org` there, but hotfix is only temporary solution, i want systematic one)

**Comment by TomasVotruba** [comment]
I run all 4 commands. It seems still empty:

![image](https://user-images.githubusercontent.com/924196/107636694-4af90180-6c6d-11eb-893d-7f10a9e081b8.png)

Systematic solution is needed :+1:

**Comment by JanMikes** [comment]
Just one more last desperate attempt before i dive into it:
- `docker exec -it getrectororg_web_1 bash` (this will get you into container)
- `echo $HOST_DEMO_DIR`
- (`exit`) :-)

**Comment by TomasVotruba** [comment]
Better :) 

![image](https://user-images.githubusercontent.com/924196/107637057-dbcfdd00-6c6d-11eb-8786-488f6254a328.png)

**Comment by TomasVotruba** [comment]
I'll try to check the browser and submit form now...

**Comment by JanMikes** [comment]
I see, for some reason https://github.com/rectorphp/getrector.org/blob/master/docker-compose.yml#L17 it does not resolve `${PWD}`. Can you please share your docker-compose version?

`docker-compose -v`

**Comment by TomasVotruba** [comment]
```
docker-compose -v
docker-compose version 1.25.0, build unknown
```

**Comment by JanMikes** [comment]
@TomasVotruba please try:
- `git fetch -p && git checkout issue-265/docker-compose-do-not-use-envfile && git pull --rebase`
- `docker-compose down`
- `docker-compose up`
- run demo form

Credits for this idea 
```diff
-           HOST_DEMO_DIR: "${PWD}/var/demo"
+           HOST_DEMO_DIR: "./var/demo"
```
Goes to @janatjak

**Comment by JanMikes** [comment]
Btw, might be related to https://unix.stackexchange.com/questions/3507/difference-between-shell-variables-which-are-exported-and-those-which-are-not-in (maybe?) 

So you can give it one more try (on master branch this time 😄 )
```
export PWD=$PWD
docker-compose down
docker-compose up
```

**Comment by TomasVotruba** [comment]
I'll try :) 

It would be better in just copy-paste form with `sudo`. Now I have to copy paste every single line and pre-type it

```bash
git fetch -p && git checkout issue-265/docker-compose-do-not-use-envfile && git pull --rebase
sudo docker-compose down
sudo docker-compose up
```

**Comment by TomasVotruba** [comment]
New error :partying_face: 

![image](https://user-images.githubusercontent.com/924196/107715657-110d1700-6cd0-11eb-92b0-343ebc1e39e7.png)


```
Fatal error: docker: Error response from daemon: create ./var/demo/qdi7c7ovnlewh2ltpog0: "./var/demo/qdi7c7ovnlewh2ltpog0" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
Error: No such container: qdi7c7ovnlewh2ltpog0
```

**Comment by TomasVotruba** [comment]
Trying on `master`: 

```bash
export PWD=$PWD
sudo docker-compose down
sudo docker-compose up
```

**Comment by TomasVotruba** [comment]
Trying on `master`: 

```bash
export PWD=$PWD
sudo docker-compose down
sudo docker-compose up
```

**Comment by TomasVotruba** [comment]
I'll have to revert soon, to be able to work. For me the working solution is better than "perfect" :)

**Comment by JanMikes** [comment]
> It would be better in just copy-paste form with sudo

Ah, i see. I highly recommend adding your user to `docker` group (https://www.thegeekdiary.com/run-docker-as-a-non-root-user/): `sudo usermod -aG docker [non-root user]`.

It will save you a lot of hair tearing 😄 

> I'll have to revert soon, to be able to work on website. For me the working solution is better than "perfect" :)

Totally understood and agreed. Falling back to static default value which works for you and can be customized by others. I will spend today on prototyping new working solution replacing DIND demo mechanism with websockets as it will be very useful as well for rector CI and i have been thinking about it for long time, im so excited and will keep you updated and ask for testing once it is ready.

**Comment by TomasVotruba** [comment]
> Ah, i see. I highly recommend adding your user to docker group (thegeekdiary.com/run-docker-as-a-non-root-user): sudo usermod -aG docker [non-root user].
