### ISSUE TITLE
[demo] Offer to create issue / failing test on fatal error

### ISSUE THREAD

**Issue by ruudk** [rectorphp/getrector.org#277]
I discovered a fatal error in Rector and created a minimal failing demo https://getrector.org/demo/90b2e99c-b5bc-4f2c-92a9-c1c11d4f15b4

But I notice that there is now no option to create an issue / failing test.

Is that for a reason?

**Comment by TomasVotruba** [comment]
Current version only supports links in case there is 1+ used rules:
https://github.com/rectorphp/getrector.org/blob/e7ae3b9546fbdfbfdf38f7b47141c7776925c0da/templates/demo/demo.twig#L36-L63

Having fatal error covered too would be great :+1:

**Comment by ruudk** [comment]
I'll try to create a PR!

**Comment by ruudk** [comment]
FYI > I currently have no time / interest to fix it. Maybe someone else can take care of it?

**Comment by TomasVotruba** [comment]
No problem. Thanks for letting me know
