### ISSUE TITLE
Fatal error: Rector rule "Rector\DowngradePhp72\Rector\FuncCall\DowngradePregUnmatchedAsNullConstantRector" not found, please verify that the rule exists 

### ISSUE THREAD

**Issue by leoloso** [rectorphp/getrector.org#304]
Rule `DowngradePregUnmatchedAsNullConstantRector` has a problem, so I tried to create a bug report via getrector.org/demo, but it doesn't let me:

![Screenshot_2021-04-10 Try Rector Online Rector - Automated Way to Instantly Upgrade and Refactor any PHP code](https://user-images.githubusercontent.com/1981996/114262995-8453b080-9a15-11eb-8b46-4319e5d9a9b1.png)

The class name is correct...

**Comment by samsonasik** [comment]
latest rector seems not deployed yet

**Comment by JanMikes** [comment]
Hi, there is no “autodeploy” of rector to demo page as it requires “composer update” and commit+push composer.lock. 

It could definitely be automated. 

Previously when the demo worker used docker images it was easier to update without need of redeploying.

**Comment by TomasVotruba** [comment]
Closing as error is expected, the rule does not exist.
