### ISSUE TITLE
Missing call to action

### ISSUE THREAD

**Issue by garak** [rectorphp/getrector.org#325]
I watched https://getrector.org/ front page for a whole minute, but I failed to find a way to get rector. That should be the first thing to see on a website called "get rector"

**Comment by TomasVotruba** [comment]
Hi, sounds good. There is a Github logo for Github devs, but it's not as visible for you.

Where woud you expect to find it?

**Comment by garak** [comment]
My interpretation of Github logo is for someone that wants to contribute to the project.
If I simply want to get the binary, I expect something like "download".

**Comment by TomasVotruba** [comment]
I see. In this case it would be:

```bash
composer require rector/rector --dev
```

Where would you expect it on the website?

**Comment by garak** [comment]
IMHO it should be a call to action, so it should be the first thing you see.
But I guess that any point can be good, it depends on how easily you want people can find it.
