### ISSUE TITLE
Migration PHPExcel > PHPSpreadsheet not working

### ISSUE THREAD

**Issue by yoelcode** [rectorphp/getrector.org#359]
Hello,

I am trying to use the rector migration from PHPExcel to PHPSpreadsheet but it is not working.

The problem is that is not detecting any changes to do, when obviously i am using code 

that should be refactored. 

It is saying "[OK] Rector is done!", but without changes.

I followed the guide from getrector.org, that talks about do this migration in 30 minutes.

If you could take a look i will be very gratefull.

![Code_XSDMML8QkS](https://user-images.githubusercontent.com/27638953/120614310-60ca4680-c457-11eb-9b2d-ca7878173dc2.png)

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting the issue.
This is only website repository. Please report Rector code issues to: http://github.com/rectorphp/rector

Thanks!
