### ISSUE TITLE
Incorrect position of `Tests` in test fixture namespace

### ISSUE THREAD

**Issue by zingimmick** [rectorphp/getrector.org#383]
`Tests` should be in the second position, but it is in the third position now.

```diff
- namespace Rector\Php74\Tests\Rector\Property\TypedPropertyRector\Fixture;
+ namespace Rector\Tests\Php74\Rector\Property\TypedPropertyRector\Fixture;
```

https://github.com/rectorphp/getrector.org/blob/9b31560be5eda4a99de82405cc01c1ac5ec4f9bd/packages/demo/src/ValueObject/AppliedRule.php#L43

**Comment by TomasVotruba** [comment]
:+1: Makes sense. Could you send PR to fix this?

**Comment by zingimmick** [comment]
> 👍 Makes sense. Could you send PR to fix this?

I'll try to fix it somewhere today.

**Comment by TomasVotruba** [comment]
Thank you!
