### ISSUE TITLE
[demo] Can't submit examples (error 500)

### ISSUE THREAD

**Issue by liarco** [rectorphp/getrector.org#443]
The demo page seems broken: https://getrector.org/demo (error 500 when submitting)

I was trying to create a demo example to open an issue, but it fails no matter what I enter as input.

Thank you.

**Comment by TomasVotruba** [comment]
See https://github.com/rectorphp/getrector.org/pull/441

**Comment by samsonasik** [comment]
@TomasVotruba I tested locally with docker, and it seems working ok, with tweak:

1. First run, manifest.json is not generated, so I commented it
2. Run it, show the page after submit

![first](https://user-images.githubusercontent.com/459648/140647158-a457c860-b1bf-4239-8da7-872830afc1b5.png)

3. next, re-enable commented manifest.json, and it show the page with css enabled

![second](https://user-images.githubusercontent.com/459648/140647180-7b6cf31f-8781-4611-bbfd-66671cf04b7a.png)

**Comment by samsonasik** [comment]
@TomasVotruba I think manifest.json is unrelated for this, if the file not exists, even the home page will already error. On this case, only demo page that show the error on getrector.org/demo.

**Comment by samsonasik** [comment]
@liarco It seems fixed now by revert https://github.com/rectorphp/getrector.org/pull/441#issuecomment-962618473 

Thank you @TomasVotruba

**Comment by liarco** [comment]
Thank you, now it works! :)
