### ISSUE TITLE
The only button I see is "Process"? Even after pressing that I only see that button and no others?

### ISSUE THREAD

**Issue by TomasVotruba** [rectorphp/getrector.org#454]
The only button I see is "Process"? Even after pressing that I only see that button and no others?

_Originally posted by @PhilETaylor in https://github.com/rectorphp/rector/issues/6861#issuecomment-992410370_

**Comment by TomasVotruba** [comment]
Outdated

**Comment by PhilETaylor** [comment]
> Outdated

Yup - seems to be working today... Thanks.


<img width="1322" alt="Screen Shot 2022-02-18 at 14 07 51" src="https://user-images.githubusercontent.com/400092/154697734-28345152-3a86-45e0-a357-040dcdfdedcb.png">
