### ISSUE TITLE
demo page submit 500 error

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/getrector.org#461]
demo page submit button now got 500 error

https://getrector.org/demo/1ec62bbb-c11a-6c4c-8a6b-15e2ed46e704

@TomasVotruba is it related with `remove sensio fw` commit https://github.com/rectorphp/getrector.org/commit/1327899978441d8f28a20cc46d93c394c6270701 or update to rector 0.12.9 commit https://github.com/rectorphp/getrector.org/commit/9a75335f3d4dacbe65ad18b93f02bd4141d00b94 ?

**Comment by samsonasik** [comment]
@TomasVotruba revert back to retor 0.12.8 seems still error at demo page submit

https://getrector.org/demo/1ec62bdd-d843-6104-b2d1-df501327b691

Let's revert back to remove sensio fw commit.

**Comment by samsonasik** [comment]
@TomasVotruba revert the remove sensio fw seems solve the demo page submit error 

https://getrector.org/demo/1ec62bf8-bf08-6e1c-85b1-ad1b9028bf0b

🎉

**Comment by TomasVotruba** [comment]
Thank you.

Have you found, what exactly is the bug there?

**Comment by samsonasik** [comment]
I didn't try locally yet, is the error not saved or reported via email or some logging service for it?

**Comment by TomasVotruba** [comment]
Not yet. There is some @todo to add monolog, but I could not fine time to implement it
