### ISSUE TITLE
Update GithubMagicLink to refer on  rectorphp/rector-downgrade-php

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/getrector.org#618]
Update once https://github.com/rectorphp/rector-src/pull/2582 merged.

**Comment by szepeviktor** [comment]
Excuse me for the question.
What is a _GithubMagicLink_?

**Comment by samsonasik** [comment]
it is for "Create a Test" button to allow forward to create PR on demo page, for example:

1. open page https://getrector.org/demo/3c0b4c58-046c-48a8-9437-3189a989bb63
2. click "Create a Test"
3. it will create a PR for failing test case to rule applied.

**Comment by szepeviktor** [comment]
Thank you.
