### ISSUE TITLE
Error 500 on homepage

### ISSUE THREAD

**Issue by samsonasik** [rectorphp/getrector.org#691]
It seems currently there is error 500 at homepage:

![Screen Shot 2022-08-07 at 23 02 55](https://user-images.githubusercontent.com/459648/183299986-ed8f9c00-0ffd-49da-98ef-85dfd9b335af.png)

https://getrector.org/

Try locally, and it got error:

```bash

HTTP 500 Internal Server Error
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "for-companies" as such route does not exist.").
```

![Screen Shot 2022-08-07 at 23 03 35](https://user-images.githubusercontent.com/459648/183300000-b2aac50a-302a-4b42-b591-0df828b31f63.png)

**Comment by samsonasik** [comment]
@TomasVotruba it seems due to new menu you commited:

[add support link to menu, to make visible](https://github.com/rectorphp/getrector.org/commit/25537ae86ebeafb96ad6f50670600716656e0d7e)

**Comment by samsonasik** [comment]
I created PR https://github.com/rectorphp/getrector.org/pull/692 for it.

**Comment by samsonasik** [comment]
Resolved at https://github.com/rectorphp/getrector.org/pull/692

**Comment by TomasVotruba** [comment]
Thank you :+1:
