### ISSUE TITLE
Make DEMO form more secure

### ISSUE THREAD

**Issue by JanMikes** [rectorphp/getrector.org#79]
- [x] Create docker image specific for demo with warmed up cache, rector.yaml config with autoloader and disabled functions https://stackoverflow.com/questions/1865020/php-how-to-disable-dangerous-functions/31869925
- [x] Move `docker run` to bash script, and allow `www-data` user to run it with sudo, then remove docker-proxy service acessible via TCP, it is security issue

**Comment by TomasVotruba** [comment]
Thank you for all improvements
